name: Update Readme Graphics

on:
  schedule:
    - cron: '0 * * * *'

  workflow_dispatch:

permissions: write-all

jobs:
  readme-graphics:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v2.2.0
        id: snake-gif
        with:
          github_user_name: jewlexx
          outputs: dist/github-contribution-grid-snake.svg

      - uses: crazy-max/ghaction-github-pages@v3.1.0
        id: publish-snake-gif
        with:
          target_branch: snake
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: dailydotdev/action-devcard@2.0.6
        id: dailydotdev-card
        with:
          commit_filename: devcard.svg
          commit_branch: output
          devcard_id: ${{ secrets.DEVCARD_ID }}
