name: Update Readme Files [Hourly]

on:
  schedule:
    - cron: '0 * * * *'

  push: 
    branches: ['main']

  workflow_dispatch:

jobs:
  dailydev-card:
    runs-on: ubuntu-latest
    steps:
      - name: devcard
        uses: dailydotdev/action-devcard@2.0.5
        with:
          devcard_id: ${{ secrets.DEVCARD_ID }}
