# Metris is slow relative to everything else so I put in in separate workflow that runs once per day
name: Update Metrics Graphics

on:
  workflow_dispatch:
  
  schedule:
    - cron: '0 0 * * *'

  workflow_dispatch:

permissions: write-all

jobs:
  readme-graphics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        id: github-metrics
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          filename: github-metrics.svg
          committer_branch: metrics
          user: jewlexx
          template: classic
          base: activity, community, repositories
          config_timezone: Australia/Sydney
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_indepth: false
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_skipped: Notes
          plugin_languages_threshold: 0%
          plugin_lines: yes
