name: Generate Datas

on:
  schedule:
    - cron: "20 * * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: jewlexx
          svg_out_path: dist/github-contribution-grid-snake.svg
